name: 'input_dialog_demo'
publish_to: 'none'

environment:
  sdk: ^3.1.0
  flutter: '>=3.13.0'

dependencies:
  flutter: { sdk: flutter }
  input_dialog: { path: .. }

flutter:
  uses-material-design: true
