name: 'input_dialog'
description: 'The easiest way to prompt a user for text, good for prototyping'
version: 0.1.0
repository: 'https://github.com/alexeyinkin/flutter-input-dialog'

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter: { sdk: flutter }

dev_dependencies:
  total_lints: ^3.1.0
